apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: auth-mongodb
  name: auth-mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
          value: {{ .Values.DEFAULT_PASSWORD }}
        image: sqshq/piggymetrics-mongodb
        name: auth-mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
