apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.service.type: loadbalancer
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    io.kompose.service: gateway
  type: LoadBalancer
status:
  loadBalancer: {}
