apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.service.type: loadbalancer
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          value: {{ .Values.DEFAULT_PASSWORD }}
        image: sqshq/piggymetrics-gateway
        name: gateway
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
