apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.service.type: nodeport
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monitoring
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          value: {{ .Values.DEFAULT_PASSWORD }}
        image: sqshq/piggymetrics-monitoring
        name: monitoring
        ports:
        - containerPort: 8080
        - containerPort: 8989
        resources: {}
      restartPolicy: Always
status: {}
