apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.service.type: nodeport
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 8080
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: monitoring
  type: NodePort
status:
  loadBalancer: {}
