apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000
  selector:
    io.kompose.service: account-service
status:
  loadBalancer: {}
