apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          value: {{ .Values.DEFAULT_PASSWORD }}
        image: sqshq/piggymetrics-config
        name: config
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
