apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o piggymetrics -c
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: statistics-service
  name: statistics-service
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    io.kompose.service: statistics-service
status:
  loadBalancer: {}
